# Workflow based off: https://github.com/ralexander-phi/marp-to-pages

name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy images
        run: mkdir build && cp -R media build/media

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:latest
        with:
          args: --bespoke.progress slides.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: --bespoke.progress slides.md -o build/slides.pdf
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pptx)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: --bespoke.progress slides.md -o build/slides.pptx
        env:
          MARP_USER: root:root

      - name: Deploy production
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
